### ISSUE TITLE
Publish package that targets .NET Standard rather than a specific framework

### ISSUE THREAD

**Issue by mot256** [little-sharps/args#24]
Could I ask that you please publish a package that rather targets .NET Standard rather than a specific framework. That way we can use it in both .NET Core and Full .NET

If we depend on you package in .NET Core you get the following error:
Package 'Args 1.1.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.

**Comment by cbrianball** [comment]
@mot256 I've been working on this the past couple of days. Args.Core is a fork of this repo that is managed by someone else (for what appears to be the sole purpose of targeting .NET Standard). In the next couple of days I'll release an updated package (v1.2.0) that will target .net 3.5, .net 4.0, .net standard 1.3 and .net standard 2.0.

**Comment by cbrianball** [comment]
@mot256 I've released v1.2.0, it's available on [NuGet](https://www.nuget.org/packages/Args/1.2.0).
